name:                xmonad-exe
version:             0.1.0.0
github:              "ropwarejb/xmonad"
license:             BSD3
author:              "Josh Brown"
maintainer:          "example@example.com"
copyright:           "2022 ROPWARE"

extra-source-files: []

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ropwarejb/xmonad#readme>

dependencies:
- base >= 4.7 && < 5
- xmobar
- xmonad
- xmonad-contrib

library:
  source-dirs:
    - .

executables:
  xmonad-exe:
    main:                xmonad.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wdefault
    - -Wwarn
    - -Wmissing-fields
    - -with-rtsopts=-N
    dependencies:
    - xmonad-exe
    - xmobar

  xmobar-exe:
    main:                xmobar.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wdefault
    - -Wwarn
    - -Wmissing-fields
    - -with-rtsopts=-N
    dependencies:
    - xmonad-exe
    - xmobar
